### ISSUE TITLE
Updating a contract already deployed fails; (Fabric v2.0 Lifecycle)

### ISSUE THREAD

**Issue by mbwhite** [IBM-Blockchain/ansible-role-blockchain-platform-manager#132]
Using the updated playbook and roles for the Fabric v2.0 lifecycle ( #94 ) deploying a contract works correctly the first time. 

If the playbook is run a second time, an attempt is made to update the contract, but there is a failure when calculating the new sequence number.  The following error is given

```
'committed_chaincode' is undefined
```

https://github.com/IBM-Blockchain/ansible-role-blockchain-platform-manager/blob/6bccf7485ea04df4b54aa428b06be1174b8b5df5/tasks/manage-contract/calculate-sequence-number.yml#L44

**Comment by sstone1** [comment]
Fixed!

**Comment by mbwhite** [comment]
Can
